---
- name: Setup database settings for postgres
  hosts: all
  become: yes
  vars:
    app_dir: /opt/apps
    database_users:
      - { name: "sonarqube", db: "sonarqube", password: "secretsqdppass#1", schema: "sonarqube_schema" }
      - { name: "gitea", db: "gitea", password: "secretgiteadppass#1", schema: "gitea_schema" }

  tasks:
    - name: Install PostgreSQL
      dnf:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Install PostgreSQL Python dependencies
      pip:
        executable: "{{ app_dir }}/python3/bin/pip3.11"
        name:
          - psycopg2-binary

    - name: Configure PostgreSQL to use md5 authentication
      replace:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^(host\s+.*\s+.*\s+.*)peer$'
        replace: '\1md5'
      notify: Restart PostgreSQL

    - name: Allow PostgreSQL user to use socket authentication
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "local   all             postgres                                peer"
        insertafter: EOF
        state: present
      notify: Restart PostgreSQL

    - name: Set PostgreSQL to listen on all interfaces
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = '*'"
      notify: Restart PostgreSQL

    - name: Create PostgreSQL databases and users
      include_tasks: pgsql_create_db.yml
      loop: "{{ database_users }}"
      loop_control:
        loop_var: item

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted