---
- name: Setup database settings for postgres
  hosts: all
  become: yes
  vars:
    app_dir: /opt/apps
    database_users:
      - { name: "sonarqube", db: "sonarqube", password: "secretsqdppass#1", schema: "sonarqube_schema" }
      - { name: "gitea", db: "gitea", password: "secretgiteadppass#1", schema: "gitea_schema" }

  tasks:
    - name: Install PostgreSQL
      dnf:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Install PostgreSQL Python dependencies
      pip:
        executable: "{{ app_dir }}/python3/bin/pip3.11"
        name:
          - psycopg2-binary

    - name: Create PostgreSQL databases and users
      include_tasks: pgsql_create_db.yml
      loop: "{{ database_users }}"
      loop_control:
        loop_var: item

    - name: Allow password authentication for PostgreSQL users
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: "^host[ \t]+{{ item.db }}[ \t]+{{ item.name }}[ \t]+127.0.0.1/32[ \t]+ident"
        line: "host    {{ item.db }}    {{ item.name }}    127.0.0.1/32    md5"
        state: present
      loop: "{{ database_users }}"
      notify: Restart PostgreSQL

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted