- hosts: all
  gather_facts: yes
  connection: ssh
  become: yes
  become_method: sudo
  become_user: opc
  vars:
    ansible_user: "{{ lookup('env', 'VM_USERNAME') }}"
    app_user: "{{ lookup('env', 'APP_USER') }}"
    remote_user: "{{ lookup('env', 'VM_USERNAME') }}"
    s3_bucket: "{{ lookup('env', 'AWS_S3_BUCKET_REPOSITORY') }}"
    aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    aws_default_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'VM_SSH_KEY') }}"
    service_name: "{{ lookup('env', 'SERVICE_NAME') }}"
    jar_timestamp: "{{ lookup('env', 'JAR_TIMESTAMP') }}"
    datasource_url: "{{ lookup('env', 'DATASOURCE_URL') }}"
    db_username: "{{ lookup('env', 'DB_USERNAME') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"


    jar_path: "/opt/apps/{{ service_name }}"
    jar_file: "/opt/apps/{{ service_name }}/{{ service_name }}.jar"
    java_home: "/opt/apps/openjdk21"
    java_url: "https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz"
    s3_artifact_path: "artifacts/{{ jar_timestamp }}/backend/{{ service_name }}.jar"
  pre_tasks:
    - name: Ensure appadm owns application directories
      file:
        path: "{{ jar_path }}"
        state: directory
        owner: appadm
        group: appadm
        mode: "0755"
      become: yes
      become_user: root
  roles:
    - { role: java_setup, become: yes, become_user: appadm }       # Run as appadm (no sudo)
    - { role: deploy_jar, become: yes, become_user: appadm }  # Run as appadm (no sudo)
    - { role: setup_service, become: yes, become_user: root }       # Run as opc (sudo required)
