- name: Ensure application directory exists
  file:
    path: "{{ jar_path }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Ensure boto3 and botocore are installed
  pip:
    name: boto3,botocore
    state: present

- name: Download JAR from S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_artifact_path }}"
    dest: "{{ jar_file }}"
    mode: get
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_DEFAULT_REGION: "{{ aws_default_region }}"
  register: jar_download